# Generated by Django 2.0.10 on 2019-02-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnscripture", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitenotice",
            name="language_code",
            field=models.CharField(choices=[("en", "English"), ("tr", "Turkçe")], default="en", max_length=10),
        ),
    ]
