# Generated by Django 3.1.6 on 2021-03-14 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0005_donationdrive_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="payments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
