# Generated by Django 1.11.6 on 2018-03-26 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0003_auto_20171208_0412"),
        ("scores", "0007_auto_20171018_0658"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionlog",
            name="award",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="awards.Award"
            ),
        ),
    ]
