# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20171208_0412'),
        ('scores', '0007_auto_20171018_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='award',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.Award'),
        ),
    ]
