# Generated by Django 1.11.6 on 2018-03-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0008_actionlog_award"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionlog",
            name="award",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="awards.Award"
            ),
        ),
    ]
