# Generated by Django 1.11.6 on 2017-12-08 03:24

from django.db import migrations


def forwards(apps, schema_editor):
    Event = apps.get_model("events.Event")
    Event.objects.filter(event_type="1").update(event_type="GENERAL")
    Event.objects.filter(event_type="2").update(event_type="NEW_ACCOUNT")
    Event.objects.filter(event_type="3").update(event_type="AWARD_RECEIVED")
    Event.objects.filter(event_type="4").update(event_type="POINTS_MILESTONE")
    Event.objects.filter(event_type="5").update(event_type="VERSES_STARTED_MILESTONE")
    Event.objects.filter(event_type="6").update(event_type="VERSES_FINISHED_MILESTONE")
    Event.objects.filter(event_type="7").update(event_type="VERSE_SET_CREATED")
    Event.objects.filter(event_type="8").update(event_type="STARTED_LEARNING_VERSE_SET")
    Event.objects.filter(event_type="9").update(event_type="AWARD_LOST")
    Event.objects.filter(event_type="10").update(event_type="GROUP_JOINED")
    Event.objects.filter(event_type="11").update(event_type="GROUP_CREATED")
    Event.objects.filter(event_type="12").update(event_type="STARTED_LEARNING_CATECHISM")
    Event.objects.filter(event_type="13").update(event_type="NEW_COMMENT")


def backwards(apps, schema_editor):
    Event = apps.get_model("events.Event")
    Event.objects.filter(event_type="GENERAL").update(event_type="1")
    Event.objects.filter(event_type="NEW_ACCOUNT").update(event_type="2")
    Event.objects.filter(event_type="AWARD_RECEIVED").update(event_type="3")
    Event.objects.filter(event_type="POINTS_MILESTONE").update(event_type="4")
    Event.objects.filter(event_type="VERSES_STARTED_MILESTONE").update(event_type="5")
    Event.objects.filter(event_type="VERSES_FINISHED_MILESTONE").update(event_type="6")
    Event.objects.filter(event_type="VERSE_SET_CREATED").update(event_type="7")
    Event.objects.filter(event_type="STARTED_LEARNING_VERSE_SET").update(event_type="8")
    Event.objects.filter(event_type="AWARD_LOST").update(event_type="9")
    Event.objects.filter(event_type="GROUP_JOINED").update(event_type="10")
    Event.objects.filter(event_type="GROUP_CREATED").update(event_type="11")
    Event.objects.filter(event_type="STARTED_LEARNING_CATECHISM").update(event_type="12")
    Event.objects.filter(event_type="NEW_COMMENT").update(event_type="13")


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20171208_0323"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
