# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 03:53
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Event = apps.get_model('events.Event')
    # There were very few of these:
    Event.objects.filter(event_type="GENERAL").delete()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20171208_0353'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
