# Generated by Django 1.11.6 on 2017-12-08 04:20

from django.db import migrations


def forwards(apps, schema_editor):
    Event = apps.get_model("events.Event")
    for e in Event.objects.filter(event_type__in=["AWARD_RECEIVED", "AWARD_LOST"]):
        if "reigning weekly champion" in e.message_html.lower():
            e.event_data["award_type"] = "REIGNING_WEEKLY_CHAMPION"
            e.event_data["temporary_award"] = True
            e.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_auto_20171208_0353"),
        ("awards", "0003_auto_20171208_0412"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
