# Generated by Django 1.11.6 on 2018-01-25 12:02

from django.db import migrations


def forwards(apps, schema_editor):
    Event = apps.get_model("events.Event")
    for event in Event.objects.filter(event_type__in=["GROUP_JOINED", "GROUP_CREATED", "NEW_COMMENT"]):
        if "group_id" in event.event_data:
            event.group_id = event.event_data["group_id"]
            event.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_event_group"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
