#!/bin/bash

. /home/cciw/webapps/learnscripture_staging_django/venv/bin/activate

LD_LIBRARY_PATH=/home2/cciw/webapps/learnscripture_staging_django/apache2/lib /home2/cciw/webapps/learnscripture_staging_django/apache2/bin/httpd.worker -f /home2/cciw/webapps/learnscripture_staging_django/apache2/conf/httpd.conf -k start
