# See https://moz-l10n-config.readthedocs.io/en/latest/fileformat.html

basepath = "."

locales = [
    "en",
    "tr",
    "es",
    "nl",
]

[[paths]]

reference = "src/learnscripture/locales/en/**/*.ftl"
l10n = "src/learnscripture/locales/{locale}/**/*.ftl"
locales = [
    "tr",
    "es",
    "nl",
]
