# Generated by Django 1.11.1 on 2017-06-02 11:22
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_auto_20150627_1257"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"base_manager_name": "objects"},
        ),
    ]
