# Generated by Django 2.0.10 on 2019-02-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_auto_20170602_1122"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationdrive",
            name="language_code",
            field=models.CharField(choices=[("en", "English"), ("tr", "Turkçe")], default="en", max_length=10),
        ),
    ]
