# Generated by Django 2.0.10 on 2019-06-22 11:42

from django.db import migrations


def forwards(apps, schema_editor):
    # Removed after the fiber app was deleted, because the data migration can no
    # longer work and is not needed.
    pass


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
