# Generated by Django 2.0.10 on 2019-06-27 10:37

from django.db import migrations, models

import cms.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_auto_20190627_0910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentitem",
            name="content_html",
            field=cms.utils.fields.CmsHTMLField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
