# Generated by Django 2.0.10 on 2019-06-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_remove_page_show_in_menu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="mark_current_regexes",
        ),
    ]
