# Generated by Django 2.0.10 on 2019-06-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_remove_page_mark_current_regexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="doc_title",
        ),
    ]
