# Generated by Django 2.0.10 on 2019-06-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_remove_page_doc_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='protected',
        ),
        migrations.RemoveField(
            model_name='page',
            name='protected',
        ),
    ]
