# Generated by Django 2.0.10 on 2019-06-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20190629_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('tr', 'Turkçe')], default='en', max_length=10)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='cms.Page')),
            ],
        ),
    ]
