# Generated by Django 2.0.10 on 2019-06-29 17:57

from django.db import migrations


def forwards(apps, schema_editor):
    Page = apps.get_model('cms', 'Page')
    PageTitle = apps.get_model('cms', 'PageTitle')
    for p in Page.objects.all():
        PageTitle.objects.create(
            page=p,
            title=p.title,
            language_code='en'
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_pagetitle'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
