# Generated by Django 2.0.10 on 2019-06-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_populate_pagetitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
