# Generated by Django 2.0.10 on 2019-06-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_remove_page_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagetitle',
            unique_together={('page', 'language_code')},
        ),
    ]
