# Generated by Django 2.0.10 on 2019-06-30 12:40

from django.db import migrations


def forwards(apps, schema_editor):
    ContentItem = apps.get_model('cms', 'ContentItem')
    Content = apps.get_model('cms', 'Content')
    for c in ContentItem.objects.all():
        Content.objects.create(
            content_item=c,
            content_html=c.content_html,
            language_code='en'
        )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20190630_1240'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
