# Generated by Django 1.11.4 on 2017-09-05 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0005_auto_20170608_1219"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actionlog",
            old_name="reference",
            new_name="localized_reference",
        ),
    ]
