# Generated by Django 1.11.4 on 2017-10-20 09:59

from django.db import migrations

from bibleverses.models import make_verse_set_passage_id


def forwards(apps, schema_editor):
    VerseSet = apps.get_model("bibleverses.VerseSet")
    i = 0
    for vs in VerseSet.objects.filter(set_type=2).prefetch_related("verse_choices"):  # PASSAGE
        i += 1
        verse_choices = list(vs.verse_choices.all())
        verse_choices.sort(key=lambda vc: vc.set_order)
        try:
            vs.passage_id = make_verse_set_passage_id(
                verse_choices[0].internal_reference, verse_choices[-1].internal_reference
            )
        except Exception:
            print(
                "Skipping VerseSet {} with invalid verse list {}".format(
                    vs.id, ", ".join(vc.internal_reference for vc in verse_choices)
                )
            )
            continue
        vs.save()
        if i % 100 == 0:
            print(i)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0021_remove_versechoice_localized_reference"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
