# Generated by Django 1.11.6 on 2017-10-24 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0022_auto_20171020_0959"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merged_from",
                to="bibleverses.Verse",
            ),
        ),
    ]
