# Generated by Django 1.11.6 on 2017-12-04 10:40

from django.db import migrations


def forwards(apps, schema_editor):
    VerseSet = apps.get_model("bibleverses.VerseSet")
    VerseSet.objects.filter(set_type="1").update(set_type="SELECTION")
    VerseSet.objects.filter(set_type="2").update(set_type="PASSAGE")


def backwards(apps, schema_editor):
    VerseSet = apps.get_model("bibleverses.VerseSet")
    VerseSet.objects.filter(set_type="SELECTION").update(set_type="1")
    VerseSet.objects.filter(set_type="PASSAGE").update(set_type="2")


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0024_auto_20171204_1040"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
