# Generated by Django 1.11.6 on 2018-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0032_verseset_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verseset",
            name="language_code",
            field=models.CharField(choices=[("en", "English"), ("tr", "Türkçe")], max_length=2),
        ),
    ]
