# Generated by Django 1.11.6 on 2018-01-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0033_auto_20180118_0544"),
    ]

    operations = [
        migrations.AddField(
            model_name="userversestatus",
            name="early_review_requested",
            field=models.BooleanField(default=False),
        ),
    ]
