# Generated by Django 3.2.9 on 2023-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0058_auto_20230211_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordsuggestiondata",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("nl", "Nederlands"), ("tr", "Türkçe"), ("es", "Español")],
                default="en",
                max_length=2,
            ),
        ),
    ]
