# Generated by Django 3.2.9 on 2022-04-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_comment_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="message",
            field=models.CharField(max_length=10000),
        ),
    ]
