# Generated by Django 1.11.1 on 2017-06-02 11:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0005_auto_20161212_0706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versechoice",
            options={"base_manager_name": "objects"},
        ),
    ]
