# Generated by Django 1.11.1 on 2017-06-03 11:44
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0006_auto_20170602_1122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verse",
            name="text_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
