# Generated by Django 1.11.4 on 2017-10-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0014_auto_20170924_1844"),
    ]

    operations = [
        migrations.AddField(
            model_name="verse",
            name="merged_into",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="bibleverses.Verse"
            ),
        ),
    ]
