# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleverses', '0016_auto_20171018_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='versechoice',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
