# Generated by Django 1.11.4 on 2017-10-18 06:54

from django.db import migrations

from bibleverses.languages import LANGUAGE_CODE_EN
from bibleverses.parsing import parse_validated_localized_reference


def forwards(apps, schema_editor):
    VerseChoice = apps.get_model("bibleverses.VerseChoice")
    i = 0
    for vc in VerseChoice.objects.all():
        parsed_ref = parse_validated_localized_reference(LANGUAGE_CODE_EN, vc.localized_reference)
        vc.internal_reference = parsed_ref.to_internal().canonical_form()
        vc.save()
        i += 1
        if i % 100 == 0:
            print(i)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0017_auto_20171018_0654"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
