# Generated by Django 1.11.6 on 2017-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0025_auto_20171204_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textversion",
            name="text_type",
            field=models.CharField(
                choices=[("BIBLE", "Bible"), ("CATECHISM", "Catechism")], default="BIBLE", max_length=20
            ),
        ),
    ]
