# Generated by Django 1.11.6 on 2018-01-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0028_verse_gapless_bible_verse_number"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="verse",
            unique_together={
                ("version", "bible_verse_number"),
                ("gapless_bible_verse_number", "version"),
                ("version", "localized_reference"),
            },
        ),
    ]
