# Generated by Django 1.11.6 on 2018-01-04 12:10

from django.db import migrations


def forwards(apps, schema_editor):
    TextVersion = apps.get_model("bibleverses.TextVersion")
    for version in TextVersion.objects.all():
        print(version.slug)
        idx = 0
        verses = version.verse_set.exclude(missing=True).filter(merged_into__isnull=True).order_by("bible_verse_number")
        for v in verses:
            v.gapless_bible_verse_number = idx
            v.save()
            idx += 1
            if idx % 1000 == 0:
                print(idx)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bibleverses", "0029_auto_20180104_1210"),
    ]

    operations = [migrations.RunPython(forwards, backwards)]
