# Generated by Django 1.11.6 on 2018-01-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0031_auto_20180104_1338"),
    ]

    operations = [
        migrations.AddField(
            model_name="verseset",
            name="language_code",
            field=models.CharField(choices=[("en", "English"), ("tr", "Türkçe")], default="en", max_length=2),
        ),
    ]
