# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 07:25
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations


def forwards(apps, schema_editor):
    # Fix up bad data caused by bug fixed in c5b66a475c6e
    # - harder fixes
    import accounts.memorymodel as MM

    UserVerseStatus = apps.get_model('bibleverses.UserVerseStatus')
    for uvs in UserVerseStatus.objects.filter(next_test_due__isnull=True,
                                              last_tested__isnull=False):
        print("Fixing UVS.next_test_due", uvs.id, uvs.localized_reference)
        if uvs.strength > 0 and uvs.last_tested is not None:
            next_test_due = uvs.last_tested + timedelta(seconds=MM.next_test_due_after(uvs.strength))
            uvs.next_test_due = next_test_due
            uvs.save()
        elif uvs.last_tested is None and uvs.strength == 0:
            uvs.next_test_due = None
            uvs.save()
        else:
            print("Unable to find match")
            1 / 0  # rollback transaction


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bibleverses', '0035_auto_20180222_0626'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
