# Generated by Django 2.0.10 on 2019-02-05 17:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0036_auto_20180222_0725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordsuggestiondata",
            name="suggestions",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
