# Generated by Django 2.0.10 on 2019-05-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleverses', '0039_auto_20190312_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseset',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe')], max_length=2, verbose_name='Language'),
        ),
    ]
