# Generated by Django 2.2.4 on 2020-05-31 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleverses', '0045_correct_for_missing_verse_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='userversestatus',
            name='internal_reference_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
