# Generated by Django 3.0.8 on 2020-07-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0048_populate_userversestatus_internal_reference_list_catechisms"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="verse",
            unique_together={("version", "localized_reference")},
        ),
    ]
