# Generated by Django 2.2.14 on 2020-07-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleverses', '0049_auto_20200724_0333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verse',
            unique_together={('version', 'bible_verse_number'), ('version', 'localized_reference'), ('version', 'gapless_bible_verse_number')},
        ),
    ]
