# Generated by Django 3.2.9 on 2022-10-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0054_userversestatus_one_uvs_for_identity_ref_version_without_verseset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textversion",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("nl", "Nederlands"), ("tr", "Türkçe")], default="en", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="verseset",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("nl", "Nederlands"), ("tr", "Türkçe")],
                help_text="The language used in the ‘Name’, ‘Description’ and ‘Additional info’ fields.",
                max_length=2,
                verbose_name="Language",
            ),
        ),
    ]
