# Generated by Django 3.2.9 on 2022-10-23 19:16

from django.db import migrations


def forwards(apps, schema_editor):
    for m in ["Verse", "UserVerseStatus"]:
        model = apps.get_model("bibleverses", m)
        for instance in model.objects.filter(localized_reference__startswith="Psalmen "):
            instance.localized_reference = instance.localized_reference.replace("Psalmen ", "Psalm ")
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0055_auto_20221022_2023"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop, elidable=True)]
