# Generated by Django 3.2.9 on 2023-02-08 21:09
from django.db import migrations


def forwards(apps, schema_editor):
    for m, attr in [
        ("Verse", "localized_reference"),
        ("UserVerseStatus", "localized_reference"),
        ("VerseSet", "name"),
    ]:
        model = apps.get_model("bibleverses", m)
        for instance in model.objects.filter(**{f"{attr}__startswith": "Mezmur "}):
            setattr(instance, attr, getattr(instance, attr).replace("Mezmur ", "Mezmurlar "))
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bibleverses", "0056_fix_psalms_name"),
    ]

    operations = [migrations.RunPython(forwards, migrations.RunPython.noop, elidable=True)]
