# Generated by Django 4.1.7 on 2025-11-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleverses', '0061_remove_wordsuggestiondata_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textversion',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Nederlands'), ('tr', 'Türkçe'), ('es', 'Español'), ('zh', '中文（繁體）'), ('zh-Hans', '中文（简体）')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='verseset',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Nederlands'), ('tr', 'Türkçe'), ('es', 'Español'), ('zh', '中文（繁體）'), ('zh-Hans', '中文（简体）')], help_text='The language used in the ‘Name’, ‘Description’ and ‘Additional info’ fields.', max_length=10, verbose_name='Language'),
        ),
    ]
