# Generated by Django 1.11.6 on 2017-10-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_account_has_installed_android_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="desktop_testing_method",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Type whole word - recommended for full keyboards and normal typing skills"),
                    (1, "Type first letter - recommended for slower typers"),
                    (
                        2,
                        "Choose from word list - recommended for handheld devices. Only available for English translations",
                    ),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="touchscreen_testing_method",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Type whole word - recommended for full keyboards and normal typing skills"),
                    (1, "Type first letter - recommended for slower typers"),
                    (
                        2,
                        "Choose from word list - recommended for handheld devices. Only available for English translations",
                    ),
                ],
                default=2,
            ),
        ),
    ]
