# Generated by Django 1.11.6 on 2017-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auto_20171128_1830"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="heatmap_default_show",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="identity",
            name="heatmap_default_stats_type",
            field=models.CharField(
                choices=[
                    ("VERSES_STARTED", "Items started"),
                    ("VERSES_TESTED", "Items tested"),
                    ("COMBINED", "Combined"),
                ],
                default="COMBINED",
                max_length=20,
            ),
        ),
    ]
