# Generated by Django 1.11.6 on 2017-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auto_20171130_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="desktop_testing_method",
            field=models.CharField(
                choices=[
                    ("FULL_WORDS", "Type whole word - recommended for full keyboards and normal typing skills"),
                    ("FIRST_LETTER", "Type first letter - recommended for slower typers"),
                    (
                        "ON_SCREEN",
                        "Choose from word list - recommended for handheld devices. Only available for English translations",
                    ),
                ],
                default="FULL_WORDS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="touchscreen_testing_method",
            field=models.CharField(
                choices=[
                    ("FULL_WORDS", "Type whole word - recommended for full keyboards and normal typing skills"),
                    ("FIRST_LETTER", "Type first letter - recommended for slower typers"),
                    (
                        "ON_SCREEN",
                        "Choose from word list - recommended for handheld devices. Only available for English translations",
                    ),
                ],
                default="ON_SCREEN",
                max_length=20,
            ),
        ),
    ]
