# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171130_1210'),
        ('accounts', '0011_auto_20171222_0949'),
    ]

    operations = [
    ]
