# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180213_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='seen_help_tour',
            field=models.BooleanField(default=False),
        ),
    ]
