# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 06:39
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    pass

    # from accounts.models import notify_all_identities
    # notify_all_identities(
    #     'The LearnScripture learning and review page has been upgraded!<br> '
    #     'If you have any problems, please leave a message on the <a href="https://learnscripture.net/groups/website-help/">Website Help</a> group.',
    # )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180301_0615'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
