# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180301_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='desktop_testing_method',
            field=models.CharField(choices=[('FULL_WORDS', 'Type whole word - most thorough'), ('FIRST_LETTER', 'Type first letter - faster'), ('ON_SCREEN', 'Choose from word list - recommended for handheld devices. Only available for English translations')], default='FULL_WORDS', max_length=20),
        ),
        migrations.AlterField(
            model_name='identity',
            name='enable_vibration',
            field=models.BooleanField(default=True, help_text='Depends on device capabilities.', verbose_name='Vibrate on mistakes'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='touchscreen_testing_method',
            field=models.CharField(choices=[('FULL_WORDS', 'Type whole word - most thorough'), ('FIRST_LETTER', 'Type first letter - faster'), ('ON_SCREEN', 'Choose from word list - recommended for handheld devices. Only available for English translations')], default='ON_SCREEN', max_length=20),
        ),
    ]
