# Generated by Django 1.11.6 on 2018-10-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_identity_interface_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="last_reminder_sent",
        ),
        migrations.RemoveField(
            model_name="account",
            name="remind_after",
        ),
        migrations.RemoveField(
            model_name="account",
            name="remind_every",
        ),
    ]
