# Generated by Django 2.0.10 on 2019-03-12 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_auto_20181030_0745"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date joined"),
        ),
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Last name"),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Password"),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=100, unique=True, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="account",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Account",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date created"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="default_bible_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bibleverses.TextVersion",
                verbose_name="Default bible version",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="desktop_testing_method",
            field=models.CharField(
                choices=[
                    ("FULL_WORDS", "Type whole word - most thorough"),
                    ("FIRST_LETTER", "Type first letter - faster"),
                    (
                        "ON_SCREEN",
                        "Choose from word list - recommended for  handheld devices. Only available for English translations",
                    ),
                ],
                default="FULL_WORDS",
                max_length=20,
                verbose_name="Desktop testing method",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="enable_animations",
            field=models.BooleanField(default=True, verbose_name="Enable animations"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="enable_sounds",
            field=models.BooleanField(default=False, verbose_name="Enable sounds"),
        ),
        migrations.AlterField(
            model_name="identity",
            name="interface_theme",
            field=models.CharField(
                choices=[
                    ("calm", "Slate"),
                    ("bubblegum", "Bubblegum pink"),
                    ("bubblegum2", "Bubblegum green"),
                    ("space", "Space"),
                ],
                default="calm",
                max_length=30,
                verbose_name="Interface theme",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="touchscreen_testing_method",
            field=models.CharField(
                choices=[
                    ("FULL_WORDS", "Type whole word - most thorough"),
                    ("FIRST_LETTER", "Type first letter - faster"),
                    (
                        "ON_SCREEN",
                        "Choose from word list - recommended for  handheld devices. Only available for English translations",
                    ),
                ],
                default="ON_SCREEN",
                max_length=20,
                verbose_name="Touchscreen testing method",
            ),
        ),
    ]
