# Generated by Django 2.0.10 on 2019-04-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20190312_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_webmaster',
            field=models.BooleanField(default=False),
        ),
    ]
