# Generated by Django 2.0.10 on 2019-06-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_account_is_webmaster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_webmaster",
        ),
    ]
