# Generated by Django 3.2.9 on 2023-02-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_auto_20211125_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="desktop_testing_method",
            field=models.CharField(
                choices=[
                    ("FULL_WORDS", "Type whole word - most thorough"),
                    ("FIRST_LETTER", "Type first letter - faster"),
                    (
                        "ON_SCREEN",
                        "Choose from word list - recommended for  handheld devices. Not available for all translations.",
                    ),
                ],
                default="FIRST_LETTER",
                max_length=20,
                verbose_name="Desktop testing method",
            ),
        ),
        migrations.AlterField(
            model_name="identity",
            name="touchscreen_testing_method",
            field=models.CharField(
                choices=[
                    ("FULL_WORDS", "Type whole word - most thorough"),
                    ("FIRST_LETTER", "Type first letter - faster"),
                    (
                        "ON_SCREEN",
                        "Choose from word list - recommended for  handheld devices. Not available for all translations.",
                    ),
                ],
                default="FIRST_LETTER",
                max_length=20,
                verbose_name="Touchscreen testing method",
            ),
        ),
    ]
