# Generated by Django 4.1.7 on 2023-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0034_auto_20230213_1117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="interface_language",
            field=models.CharField(
                choices=[("en", "English"), ("tr", "Türkçe"), ("es", "Español")],
                default="en",
                max_length=10,
                verbose_name="Interface language",
            ),
        ),
    ]
