# Generated by Django 5.2.16 on 2026-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_alter_identity_interface_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="interface_language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Türkçe"),
                    ("es", "Español"),
                    ("nl", "Nederlands"),
                ],
                default="en",
                max_length=10,
                verbose_name="Interface language",
            ),
        ),
    ]
