# Generated by Django 1.11.6 on 2017-11-28 18:30

from django.db import migrations

forwards = """
ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey;
ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES accounts_account(id) DEFERRABLE INITIALLY DEFERRED;

DROP TABLE IF EXISTS auth_user_groups;
DROP TABLE IF EXISTS auth_user_user_permissions;
DROP TABLE IF EXISTS piston_nonce;
DROP TABLE IF EXISTS piston_token;
DROP TABLE IF EXISTS piston_consumer;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_auto_20171027_1336"),
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(forwards, ""),
    ]
