# Generated by Django 1.11.6 on 2018-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_identity_seen_help_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identity",
            name="new_learn_page",
            field=models.BooleanField(default=True, verbose_name="Use new learn page"),
        ),
    ]
