# Generated by Django 1.11.6 on 2018-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_auto_20181023_0752"),
    ]

    operations = [
        migrations.AddField(
            model_name="identity",
            name="interface_language",
            field=models.CharField(
                choices=[("en", "English"), ("tr", "Turkçe")],
                default="en",
                max_length=10,
                verbose_name="Interface language",
            ),
        ),
    ]
