# Generated by Django 4.1.7 on 2023-04-22 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("groups", "0011_group_quietened"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[("group_quietened", "Group quietened"), ("group_unquietened", "Group unquietened")],
                        max_length=50,
                    ),
                ),
                ("done_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions_taken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to="groups.group",
                    ),
                ),
            ],
        ),
    ]
