# Generated by Django 4.1.7 on 2023-04-23 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationaction",
            name="duration",
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="moderationaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("group_quietened", "Group quietened"),
                    ("group_unquietened", "Group unquietened"),
                    ("user_hellbanned", "User hellbanned"),
                    ("user_unhellbanned", "User unhellbanned"),
                ],
                max_length=50,
            ),
        ),
    ]
