# Generated by Django 4.1.7 on 2023-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnscripture", "0003_alter_sitenotice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenotice",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("tr", "Türkçe"), ("es", "Español")], default="en", max_length=10
            ),
        ),
    ]
