# Generated by Django 5.2.16 on 2026-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learnscripture", "0004_alter_sitenotice_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitenotice",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Türkçe"),
                    ("es", "Español"),
                    ("nl", "Nederlands"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
