# Generated by Django 2.0.10 on 2019-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0006_auto_20190517_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="open",
            field=models.BooleanField(default=False, verbose_name="Open"),
        ),
        migrations.AlterField(
            model_name="group",
            name="public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
    ]
