# Generated by Django 5.2.16 on 2026-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0011_group_quietened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="language_code",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("tr", "Türkçe"),
                    ("es", "Español"),
                    ("nl", "Nederlands"),
                ],
                default="en",
                help_text="The main language used in the group",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
