# Generated by Django 2.0.10 on 2019-05-17 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0005_auto_20190517_1120"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="language",
            new_name="language_code",
        ),
    ]
