# Generated by Django 3.2.9 on 2021-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0008_auto_20210314_1208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
