# Generated by Django 4.1.7 on 2023-04-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0009_auto_20211125_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="language_code",
            field=models.CharField(
                choices=[("en", "English"), ("tr", "Türkçe"), ("es", "Español")],
                default="en",
                help_text="The main language used in the group",
                max_length=10,
                verbose_name="Language",
            ),
        ),
    ]
