# Generated by Django 4.1.7 on 2023-04-24 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0005_alter_comment_message"),
        ("moderation", "0004_alter_moderationaction_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderationaction",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moderation_actions",
                to="comments.comment",
            ),
        ),
        migrations.AlterField(
            model_name="moderationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("group_quietened", "Group quietened"),
                    ("group_unquietened", "Group unquietened"),
                    ("user_hellbanned", "User hellbanned"),
                    ("user_unhellbanned", "User unhellbanned"),
                    ("comment_hidden", "Comment hidden"),
                ],
                max_length=50,
            ),
        ),
    ]
