# Generated by Django 2.1.11 on 2019-08-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="hidden",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
