# Generated by Django 2.0.10 on 2019-06-30 12:40

import django.db.models.deletion
from django.db import migrations, models

import cms.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0017_auto_20190630_1239"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_html", cms.utils.fields.CmsHTMLField(verbose_name="Content")),
                (
                    "language_code",
                    models.CharField(choices=[("en", "English"), ("tr", "Turkçe")], default="en", max_length=10),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="content",
            name="content_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="content_set", to="cms.ContentItem"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="content",
            unique_together={("content_item", "language_code")},
        ),
    ]
