# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 04:12
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Award = apps.get_model('awards.Award')
    Award.objects.filter(award_type="0").update(award_type="STUDENT")
    Award.objects.filter(award_type="1").update(award_type="MASTER")
    Award.objects.filter(award_type="2").update(award_type="SHARER")
    Award.objects.filter(award_type="3").update(award_type="TREND_SETTER")
    Award.objects.filter(award_type="4").update(award_type="ACE")
    Award.objects.filter(award_type="5").update(award_type="RECRUITER")
    Award.objects.filter(award_type="6").update(award_type="HACKER")
    Award.objects.filter(award_type="7").update(award_type="WEEKLY_CHAMPION")
    Award.objects.filter(award_type="8").update(award_type="REIGNING_WEEKLY_CHAMPION")
    Award.objects.filter(award_type="9").update(award_type="ADDICT")
    Award.objects.filter(award_type="10").update(award_type="ORGANIZER")
    Award.objects.filter(award_type="11").update(award_type="CONSISTENT_LEARNER")


def backwards(apps, schema_editor):
    Award = apps.get_model('awards.Award')
    Award.objects.filter(award_type="STUDENT").update(award_type="0")
    Award.objects.filter(award_type="MASTER").update(award_type="1")
    Award.objects.filter(award_type="SHARER").update(award_type="2")
    Award.objects.filter(award_type="TREND_SETTER").update(award_type="3")
    Award.objects.filter(award_type="ACE").update(award_type="4")
    Award.objects.filter(award_type="RECRUITER").update(award_type="5")
    Award.objects.filter(award_type="HACKER").update(award_type="6")
    Award.objects.filter(award_type="WEEKLY_CHAMPION").update(award_type="7")
    Award.objects.filter(award_type="REIGNING_WEEKLY_CHAMPION").update(award_type="8")
    Award.objects.filter(award_type="ADDICT").update(award_type="9")
    Award.objects.filter(award_type="ORGANIZER").update(award_type="10")
    Award.objects.filter(award_type="CONSISTENT_LEARNER").update(award_type="11")


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20171208_0412'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
